[package]
    name = "persister"
    version = "0.1.0"
    edition = "2021"

[dependencies]
    raft.workspace = true
    anyhow = "1.0.86"
    tokio = {version = "1.39.3", features = [
        "rt-multi-thread",
        "macros",
        "fs",
    ]}
    async-trait = "0.1.81"
